<?php
/*
 * Copyright (c) 2011-2012, Marc Sven Kleinböhl (Hroudtwolf) <coding4food@hroudtwolf.de>.
 * All rights reserved.
 */
 
function debux_init () {
    
  drupal_add_css (drupal_get_path ('module', 'debux') . '/css/debux.css');
  drupal_add_js (drupal_get_path ('module', 'debux') . '/js/debux_collapser.js');
 
  return;
}

function debux ($output, $level = Debux::DEBUGLEVEL_NOTICE)  {

  module_load_include ('inc', 'debux', 'includes/Debux.class');
  
  Debux::out($output, $level);
 
  return;
}

/*
 * Implements hook_preprocess_page.
 */
function debux_preprocess_page (&$variables) {

  module_load_include ('inc', 'debux', 'includes/Debux.class');

  if (! Debux::isOutputAvailable ()) {
    return;
  }
  
  if (! isset ($variables['messages'])) {
    $variables['messages'] = '';
  }
   
  $variables['messages'] .= Debux::render();
  
  return;
}

/*
 * Implements hook_theme.
 */
function debux_theme () {
  
  return array (
    'debux' => array (
      'template'  => 'templates/debux',
      'variables' => array ('output'=>array ())
    )
  );
}

/*
 * Implements hook_menu.
 */
function debux_menu () {
  
  return array (
    'node/%/debux' => array (
      'type'	          => MENU_LOCAL_TASK,
      'page arguments'	  => array (1),
      'page callback'	  => '_debux_node_console',
      'file'			  => 'includes/node_console.inc',
      'access arguments'  => array ('debux node'),
      'title'			  => 'Debux node'
    )
  );
}
